version: '3'
networks:
  monitoring:
    name: exporter-prometheus-grafana
    external: true
services:
  ubuntu-ssh-grafana:
    image: grafana/grafana:main-ubuntu
    container_name: ubuntu-grafana
    command: 
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
volumes:
  grafana-data: